# Generated by Django 3.2.16 on 2022-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20221207_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.BigIntegerField(default=1),
        ),
    ]
