# Generated by Django 3.2.16 on 2022-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_phone', models.BigIntegerField()),
                ('seller_address', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=20)),
                ('acc_holdername', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('acc_number', models.BigIntegerField()),
                ('seller_username', models.CharField(max_length=20)),
                ('seller_password', models.CharField(max_length=20)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=30),
        ),
    ]
