# Generated by Django 3.2.16 on 2022-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20221203_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default='', upload_to='customer/'),
        ),
    ]
