# Generated by Django 3.2.16 on 2022-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
